spring:
  application:
    name: order-service
    
# server:
#  port: 8201
  
#在两台eureka上都注册  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true #开启hystrix
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000   #超时时间，默认也是一秒 
            
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  #暴露端口，用来监控
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202